include $(TOPDIR)/rules.mk

PKG_NAME:=ezwifibroadcast
PKG_RELEASE:=1.6R6

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL=https://github.com/libc0607/YJSNPI-Broadcast.git
PKG_SOURCE_DATE:=2019-06-28
PKG_SOURCE_VERSION:=805b9d9b69caceb13e7cab153c94fd60cbf1bb9a

PKG_BUILD_DIR=$(BUILD_DIR)/$(PKG_NAME)/$(PKG_NAME)-$(PKG_VERSION)

include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/cmake.mk

define Package/ezwifibroadcast
  SECTION:=net
  CATEGORY:=Network
  TITLE:=ezwifibroadcast
  DEPENDS:=+librt +libpcap +coreutils +kmod-usb-net \
  +kmod-usb-net-rndis +kmod-usb2 +kmod-usb-ohci +kmod-usb-storage-extras \
  +kmod-usb-serial +kmod-usb-serial-ch341 +socat +usbutils +kmod-fs-ext4 \
  +kmod-fs-vfat +kmod-fs-autofs4 +kmod-nls-cp437 +kmod-nls-utf8\
  +kmod-nls-iso8859-1 +ntfs-3g +block-mount +mount-utils +libiniparser
endef

define Package/ezwifibroadcast/config
config PACKAGE_EZWIFIBROADCAST_PROCD
	bool "Use procd init script"
	default y
endef

define Package/ezwifibroadcast/description
 ezwifibroadcast on openwrt
endef

define Build/Configure
	 mkdir -p $(PKG_BUILD_DIR)
	# $(CP) ./src/* $(PKG_BUILD_DIR)
	 [ -d $(PKG_BUILD_DIR)/root ] && $(CP) $(PKG_BUILD_DIR)/root/wifibroadcast/* $(PKG_BUILD_DIR)/ || echo
	 [ -d $(PKG_BUILD_DIR)/root ] && rm -rf $(PKG_BUILD_DIR)/root || echo
	 [ -d $(PKG_BUILD_DIR)/boot ] && rm -rf $(PKG_BUILD_DIR)/boot || echo
	 [ -f $(PKG_BUILD_DIR)/Makefile ] && rm $(PKG_BUILD_DIR)/Makefile || echo
	 [ -f $(PKG_BUILD_DIR)/CMakeCache.txt ] && rm $(PKG_BUILD_DIR)/CMakeCache.txt || echo
	 [ -f $(PKG_BUILD_DIR)/*.o ] && rm $(PKG_BUILD_DIR)/*.o || echo
	$(call Build/Configure/Default)
endef

define Package/ezwifibroadcast/install
	$(INSTALL_DIR) $(1)/usr/sbin/
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/rssitx $(1)/usr/sbin/
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/tx_rawsock $(1)/usr/sbin/   
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/tx_measure $(1)/usr/sbin/
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/tx_telemetry $(1)/usr/sbin/
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/rx $(1)/usr/sbin/
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/rssirx $(1)/usr/sbin/
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/rssi_forward $(1)/usr/sbin/
#	$(INSTALL_BIN) $(PKG_BUILD_DIR)/rssi_write_shmem $(1)/usr/sbin/
#	$(INSTALL_BIN) $(PKG_BUILD_DIR)/rssi_forward_stdout $(1)/usr/sbin/
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/rx_status $(1)/usr/sbin/
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/check_alive $(1)/usr/sbin/
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/rx_rc_telemetry_buf $(1)/usr/sbin/
#	$(INSTALL_BIN) $(PKG_BUILD_DIR)/rx_rc_telemetry $(1)/usr/sbin/
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/sharedmem_init_rx $(1)/usr/sbin/
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/sharedmem_init_tx $(1)/usr/sbin/
#	$(INSTALL_BIN) $(PKG_BUILD_DIR)/suftees $(1)/usr/sbin/
	$(INSTALL_DIR) $(1)/etc/modules.d/
	$(INSTALL_BIN) ./files/ath9k_hw.modprobe.options $(1)/etc/modules.d/ath9k_hw
	$(INSTALL_DIR) $(1)/etc/init.d
ifdef CONFIG_PACKAGE_EZWIFIBROADCAST_PROCD
	$(INSTALL_BIN) ./files/ezwifibroadcast.init.procd $(1)/etc/init.d/ezwifibroadcast
else
	$(INSTALL_BIN) ./files/ezwifibroadcast.init $(1)/etc/init.d/ezwifibroadcast
endif
#	$(INSTALL_DIR) $(1)/etc/wbc
#	$(INSTALL_BIN) ./files/osdconfig.ini $(1)/etc/wbc
	$(INSTALL_DIR) $(1)/etc/uci-defaults
	$(INSTALL_BIN) ./files/ezwifibroadcast.defaults $(1)/etc/uci-defaults
	$(INSTALL_DIR) $(1)/etc/config
	$(INSTALL_BIN) ./files/ezwifibroadcast.config $(1)/etc/config/wbc
endef

$(eval $(call BuildPackage,ezwifibroadcast))
